<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
	    <TargetFramework>net8.0</TargetFramework>
	    <ImplicitUsings>enable</ImplicitUsings>
	    <OutputPath>..\..\..\RAerp\Plugins\RA.Categories</OutputPath>
	    <OutDir>$(OutputPath)</OutDir>
	    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Configuration.cshtml" />
    <None Remove="Views\Create.cshtml" />
    <None Remove="Views\Index.cshtml" />
    <None Remove="Views\List.cshtml" />
    <None Remove="Views\_CategoryList.cshtml" />
    <None Remove="Views\_Configuration.Main.cshtml" />
    <None Remove="Views\_Configuration.Mapping.cshtml" />
    <None Remove="Views\_CreateAndEdit.cshtml" />
    <None Remove="Views\_CreateAndEdit.General.cshtml" />
    <None Remove="Views\_CreateAndEdit.System.cshtml" />
    <None Remove="Views\_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\Configuration.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Create.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Index.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CategoryList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_Configuration.Main.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_Configuration.Mapping.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.General.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.System.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\CoreModules\RA.EntityTypes\RA.EntityTypes.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
		<ProjectReference Include="..\..\..\RAerp\RAerp.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
	</ItemGroup>

</Project>
