<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <OutputPath>..\..\RAerp\Plugins\RA.FormTypes</OutputPath>
	  <OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domain\Mappings\**" />
    <EmbeddedResource Remove="Domain\Mappings\**" />
    <None Remove="Domain\Mappings\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_FormTypeList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\Libraries\RA.Core\RA.Core.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	  <ProjectReference Include="..\..\Libraries\RA.Data\RA.Data.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	  <ProjectReference Include="..\..\RAerp\RAerp.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
  </ItemGroup>

</Project>
