using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.Core.Models.PluginModels.EntityTypes
{
    /// <summary>
    /// Base configure model of Entity
    /// </summary>
    public class BaseEntityConfigureModel
    {
        public Guid EntityTypeId { get; set; }
        public string SystemName { get; set; }
        public string Template { get; set; }
        public int TemplateIncrementCount { get; set; }
        public int TemplateCount { get; set; }
        public bool AutoGeneratedTemplate { get; set; }
        public bool CreateEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public bool DeleteEnabled { get; set; }
        public bool Installed { get; set; }
        public bool Enabled { get; set; }
        public bool AddressEnabled { get; set; }
        public bool InventoryEnabled { get; set; }
    }
}
