using Microsoft.EntityFrameworkCore;
using RA.Core.DataCaching.CacheManagement;
using RA.Data.App_Data;
using RA.EntityTypes.Data;
using RA.EntityTypes.Domain;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.EntityTypes.Services
{
    /// <summary>
    /// Base service of Entity Types where we use Generics 
    /// CRUD operations, get by Id and getList
    /// </summary>
    /// <typeparam name="TEntity">TEntity : Base Entity Type</typeparam>
    /// <typeparam name="TSettings">TSettings : Base Entity Type Settings</typeparam>
    /// <typeparam name="TContext">TContext : Context Data of Entity</typeparam>
    public class EntityTypeService<TEntity, TSettings, TContext> : IEntityTypeService<TEntity, TSettings, TContext> 
        where TEntity : BaseEntityType
        where TSettings : BaseEntityTypeSetting
        where TContext : DbContext
    {
        private readonly TContext _erpContext;
        private DbSet<TEntity> _entityDbSet;
        private readonly ICacheManager<TEntity> _cacheManager;
        private readonly IEntityTypeManager _entityTypeManager;

        public EntityTypeService(TContext erpContext,
            ICacheManager<TEntity> cacheManager,
            IEntityTypeManager entityTypeManager)
        {
            _erpContext = erpContext;
            _entityDbSet = _erpContext.Set<TEntity>();
            _cacheManager = cacheManager;
            _entityTypeManager = entityTypeManager;
        }

        public virtual async Task<TEntity> GetById(Guid id)
        {
            return await _entityDbSet.FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<IEnumerable<TEntity>> GetList(List<Guid> entityTypeIds)
        {
            return _cacheManager.EntityCacheNotExists(entityTypeIds) ? 
                _cacheManager.GenerateCache(_entityDbSet.Where(c => entityTypeIds.Contains(c.EntityTypeId)).AsEnumerable(), entityTypeIds) 
                : _cacheManager.GetEntityCacheData(entityTypeIds);
        }
        
        public virtual async Task<IEnumerable<TEntity>> GetList(Guid entityTypeId)
        {
            return _cacheManager.EntityCacheNotExists(entityTypeId) ?
                _cacheManager.GenerateCache(_entityDbSet.Where(c => c.EntityTypeId == entityTypeId).AsEnumerable(), entityTypeId) 
                : _cacheManager.GetEntityCacheData(entityTypeId);
        }

        public virtual async Task Insert(TEntity entity)
        {
            // get settings
            var settings = await _entityTypeManager.GetSettingDataOfEntity<TEntity, TSettings>(entity.EntityTypeId);
            if (settings.AutoGeneratedTemplate)
            {
                entity.Code = await _entityTypeManager.GetCurrentTemplateOfEntity<TEntity, TSettings>(entity.EntityTypeId);

                await _entityTypeManager.IncreaseTemplateCountOfEntity<TEntity, TSettings>(entity.EntityTypeId);
            }
            else
            {
                if (string.IsNullOrEmpty(settings.Template))
                {
                    // use TEMP for now
                    // will add database table for this
                    entity.Code = "TEMP001";
                }
            }

            entity.CreatedOn = DateTime.Now;
            await _entityDbSet.AddAsync(entity);
            await _erpContext.SaveChangesAsync();
            _cacheManager.ClearCache(entity.EntityTypeId);
        }

        public virtual async Task Update(TEntity entity)
        {
            entity.ModifiedOn = DateTime.Now;
            _entityDbSet.Update(entity);
            await _erpContext.SaveChangesAsync();
            _cacheManager.ClearCache(entity.EntityTypeId);
        }

        public virtual async Task Delete(TEntity entity)
        {
            entity.Deleted = true;
            entity.DeletedOn = DateTime.Now;
            _entityDbSet.Update(entity);
            await _erpContext.SaveChangesAsync();
            _cacheManager.ClearCache(entity.EntityTypeId);
        }

    }
}
