using Microsoft.EntityFrameworkCore;
using RA.Core.DataCaching.CacheManagement;
using RA.EntityTypes.Data;
using RA.EntityTypes.Domain;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;

namespace RA.EntityTypes.Services
{
    /// <summary>
    /// Base service of Entity Types where we use Generics 
    /// CRUD operations, get by Id and getList
    /// </summary>
    /// <typeparam name="TEntity">TEntity : Base Entity Type</typeparam>
    /// <typeparam name="TSettings">TSettings : Base Entity Type Settings</typeparam>
    /// <typeparam name="TContext">TContext : Context Data of Entity</typeparam>
    public class EntityTypeService<TEntity, TSettings, TContext> : IEntityTypeService<TEntity, TSettings, TContext> 
        where TEntity : BaseEntityType
        where TSettings : BaseEntityTypeSetting
        where TContext : DbContext
    {
        #region Constants
        private readonly TContext _erpContext;
        private readonly ICacheManager<TEntity> _cacheManager;
        private readonly IEntityTypeManager _entityTypeManager;
        #endregion

        #region Ctor
        public EntityTypeService(TContext erpContext,
            ICacheManager<TEntity> cacheManager,
            IEntityTypeManager entityTypeManager)
        {
            _erpContext = erpContext;
            _cacheManager = cacheManager;
            _entityTypeManager = entityTypeManager;
        }
        #endregion

        #region CRUD
        public virtual async Task<TEntity> GetByIdAsync(Guid id)
        {
            return await _erpContext.Set<TEntity>().FirstOrDefaultAsync(c => c.Id == id);
        }

        /// <summary>
        /// Get List Cache for All rows
        /// </summary>
        /// <param name="entityTypeIds"></param>
        /// <returns></returns>
        public virtual async Task<IEnumerable<TEntity>> GetListAsync(List<Guid> entityTypeIds)
        {
            if (_cacheManager.EntityCacheNotExists(entityTypeIds))
            {
                // AsNoTracking() is mandatory here to prevent IDisposable errors
                var data = await _erpContext.Set<TEntity>().Where(c => entityTypeIds.Contains(c.EntityTypeId)).AsNoTracking().ToListAsync();
                await _cacheManager.GenerateCacheAsync(data, entityTypeIds);
                return data;
            }

            return _cacheManager.GetEntityCacheData(entityTypeIds);
        }
        
        /// <summary>
        /// Get List Cache for All rows
        /// </summary>
        /// <param name="entityTypeId"></param>
        /// <returns></returns>
        public virtual async Task<IEnumerable<TEntity>> GetListAsync(Guid entityTypeId)
        {
            if (_cacheManager.EntityCacheNotExists(entityTypeId))
            {
                // AsNoTracking() is mandatory here to prevent IDisposable errors
                var data = await _erpContext.Set<TEntity>().Where(c => c.EntityTypeId == entityTypeId).AsNoTracking().ToListAsync();
                await _cacheManager.GenerateCacheAsync(data, entityTypeId);
                return data;
            }

            return _cacheManager.GetEntityCacheData(entityTypeId);
        }

        public virtual async Task InsertAsync(TEntity entity)
        {
            // get settings
            var settings = await _entityTypeManager.GetSettingDataOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);
            if (settings.AutoGeneratedTemplate)
            {
                entity.Code = await _entityTypeManager.GetCurrentTemplateOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);

                await _entityTypeManager.IncreaseTemplateCountOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);
            }
            else
            {
                if (string.IsNullOrEmpty(settings.Template))
                {
                    // use TEMP for now
                    // will add database table for this
                    entity.Code = "TEMP001";
                }
            }

            entity.Id = Guid.NewGuid();
            entity.CreatedOn = DateTime.UtcNow;
            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                await _erpContext.Set<TEntity>().AddAsync(entity);
                await _erpContext.SaveChangesAsync();
                await transaction.CommitAsync();
                _cacheManager.ClearCache(entity.EntityTypeId);
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex.InnerException?.Message ?? ex.Message);
            }
        }

        public virtual async Task UpdateAsync(TEntity entity)
        {
            entity.ModifiedOn = DateTime.UtcNow;

            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TEntity>().Update(entity);
                await _erpContext.SaveChangesAsync();
                await transaction.CommitAsync();
                _cacheManager.ClearCache(entity.EntityTypeId);
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex.InnerException?.Message ?? ex.Message);
            }
        }

        public virtual async Task DeleteAsync(TEntity entity)
        {
            entity.Deleted = true;
            entity.DeletedOn = DateTime.UtcNow;
            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TEntity>().Update(entity);
                await _erpContext.SaveChangesAsync();
                await transaction.CommitAsync();
                _cacheManager.ClearCache(entity.EntityTypeId);
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex.InnerException?.Message ?? ex.Message);
            }
        }
        #endregion

        #region Methods
        public virtual Task<List<TEntity>> ToPagedListAsync(IEnumerable<TEntity> query, int pageNumber, int pageSize)
        {
            // Default values
            if (pageNumber <= 0)
                pageNumber = 1;

            if (pageSize <= 0)
                pageSize = 10;

            // Skip rows
            var skip = (pageNumber - 1) * pageSize;

            // Fetch paged data (synchronous LINQ — works for both in-memory and EF queryables)
            var result = query.Skip(skip).Take(pageSize).ToList();

            return Task.FromResult(result);
        }
        #endregion
    }
}
