using Microsoft.EntityFrameworkCore;
using RA.Core.DataCaching.CacheManagement;
using RA.Data.App_Data;
using RA.EntityTypes.Data;
using RA.EntityTypes.Domain;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.EntityTypes.Services
{
    /// <summary>
    /// Base service of Entity Types where we use Generics 
    /// CRUD operations, get by Id and getList
    /// </summary>
    /// <typeparam name="TEntity">TEntity : Base Entity Type</typeparam>
    /// <typeparam name="TSettings">TSettings : Base Entity Type Settings</typeparam>
    /// <typeparam name="TContext">TContext : Context Data of Entity</typeparam>
    public class EntityTypeService<TEntity, TSettings, TContext> : IEntityTypeService<TEntity, TSettings, TContext> 
        where TEntity : BaseEntityType
        where TSettings : BaseEntityTypeSetting
        where TContext : DbContext
    {
        #region Constants
        private readonly TContext _erpContext;
        private readonly ICacheManager<TEntity> _cacheManager;
        private readonly IEntityTypeManager _entityTypeManager;
        #endregion

        #region Ctor
        public EntityTypeService(TContext erpContext,
            ICacheManager<TEntity> cacheManager,
            IEntityTypeManager entityTypeManager)
        {
            _erpContext = erpContext;
            _cacheManager = cacheManager;
            _entityTypeManager = entityTypeManager;
        }
        #endregion

        #region CRUD
        public virtual async Task<TEntity> GetByIdAsync(Guid id)
        {
            return await _erpContext.Set<TEntity>().FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<IEnumerable<TEntity>> GetListAsync(List<Guid> entityTypeIds)
        {
            return _cacheManager.EntityCacheNotExists(entityTypeIds) ? 
                await _cacheManager.GenerateCacheAsync(_erpContext.Set<TEntity>().Where(c => entityTypeIds.Contains(c.EntityTypeId)).AsEnumerable(), entityTypeIds) 
                : _cacheManager.GetEntityCacheData(entityTypeIds);
        }
        
        public virtual async Task<IEnumerable<TEntity>> GetListAsync(Guid entityTypeId)
        {
            return _cacheManager.EntityCacheNotExists(entityTypeId) ?
                await _cacheManager.GenerateCacheAsync(_erpContext.Set<TEntity>().Where(c => c.EntityTypeId == entityTypeId).AsEnumerable(), entityTypeId) 
                : _cacheManager.GetEntityCacheData(entityTypeId);
        }

        public virtual async Task InsertAsync(TEntity entity)
        {
            // get settings
            var settings = await _entityTypeManager.GetSettingDataOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);
            if (settings.AutoGeneratedTemplate)
            {
                entity.Code = await _entityTypeManager.GetCurrentTemplateOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);

                await _entityTypeManager.IncreaseTemplateCountOfEntityAsync<TEntity, TSettings>(entity.EntityTypeId);
            }
            else
            {
                if (string.IsNullOrEmpty(settings.Template))
                {
                    // use TEMP for now
                    // will add database table for this
                    entity.Code = "TEMP001";
                }
            }

            entity.CreatedOn = DateTime.Now;
            await _erpContext.Set<TEntity>().AddAsync(entity);
            try
            {
                await _erpContext.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                var innerMessage = ex.InnerException?.Message ?? ex.Message;
                Console.WriteLine(innerMessage); // or log it
                throw;
            }
            _cacheManager.ClearCache(entity.EntityTypeId);
        }

        public virtual async Task UpdateAsync(TEntity entity)
        {
            entity.ModifiedOn = DateTime.Now;
            _erpContext.Set<TEntity>().Update(entity);
            try
            {
                await _erpContext.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                var innerMessage = ex.InnerException?.Message ?? ex.Message;
                Console.WriteLine(innerMessage); // or log it
                throw;
            }
            _cacheManager.ClearCache(entity.EntityTypeId);
        }

        public virtual async Task DeleteAsync(TEntity entity)
        {
            entity.Deleted = true;
            entity.DeletedOn = DateTime.Now;
            _erpContext.Set<TEntity>().Update(entity);
            try
            {
                await _erpContext.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                var innerMessage = ex.InnerException?.Message ?? ex.Message;
                Console.WriteLine(innerMessage); // or log it
                throw;
            }
            _cacheManager.ClearCache(entity.EntityTypeId);
        }
        #endregion
    }
}
