using Microsoft.EntityFrameworkCore;
using RA.Core.DataCaching.CacheManagement;
using RA.Data.Data.FormTypes;
using RA.FormTypes.Data;
using RA.FormTypes.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.FormTypes.Services
{
    /// <summary>
    /// Base Service of Forms
    /// this also include CRUD of Form Item
    /// </summary>
    /// <typeparam name="TForm">Base Form</typeparam>
    /// <typeparam name="TItem">Base Form Item</typeparam>
    /// <typeparam name="TSettings">Base Form Setting</typeparam>
    /// <typeparam name="TContext">Context data of Form</typeparam>
    public class FormItemService<TForm, TItem, TSettings, TContext>
        where TForm : BaseForm
        where TItem : BaseFormItem
        where TSettings : BaseFormSetting
        where TContext : DbContext
    {
        private readonly TContext _erpContext;
        private readonly DbSet<TForm> _formDbSet;
        private readonly DbSet<TItem> _formItemDbSet;
        private readonly ICacheManager<TForm> _cacheFormManager;
        private readonly ICacheManager<TItem> _cacheFormItemManager;
        private readonly IFormTypeManager _formTypeManager;

        public FormItemService(TContext erpContext,
            ICacheManager<TForm> cacheFormManager,
            ICacheManager<TItem> cacheFormItemManager,
            IFormTypeManager formTypeManager)
        {
            _erpContext = erpContext;
            _formDbSet = _erpContext.Set<TForm>();
            _formItemDbSet = _erpContext.Set<TItem>();
            _cacheFormManager = cacheFormManager;
            _cacheFormItemManager = cacheFormItemManager;
            _formTypeManager = formTypeManager;
        }

        #region Form CRUD

        public virtual async Task<TForm> GetFormById(Guid id)
        {
            return await _formDbSet.FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<IEnumerable<TForm>> GetFormList()
        {
            return _cacheFormManager.EntityCacheNotExists(typeof(TForm).FullName) ?
                _cacheFormManager.GenerateCache(_formDbSet.Where(c => c.FormTypeSystemName == typeof(TForm).FullName).AsEnumerable(), typeof(TForm).FullName) 
                : _cacheFormManager.GetEntityCacheData(typeof(TForm).FullName);
        }

        public virtual async Task InsertForm(TForm form)
        {
            // get settings
            var settings = await _formTypeManager.GetSettingDataOfForm<TForm, TSettings>();
            if (settings.AutoGeneratedTemplate)
            {
                form.FormNbr = await _formTypeManager.GetCurrentTemplateOfForm<TForm, TSettings>();

                await _formTypeManager.IncreaseTemplateCountOfForm<TForm, TSettings>();
            }
            else
            {
                if (string.IsNullOrEmpty(settings.Template))
                {
                    // use TEMP for now
                    // will add database table for this
                    form.FormNbr = "<TEMP>";
                }
            }

            form.CreatedOn = DateTime.Now;
            await _formDbSet.AddAsync(form);
            await _erpContext.SaveChangesAsync();
            _cacheFormManager.ClearCache(typeof(TForm).FullName);
        }

        public virtual async Task UpdateForm(TForm form)
        {
            form.ModifiedOn = DateTime.Now;
            _formDbSet.Update(form);
            await _erpContext.SaveChangesAsync();
            _cacheFormManager.ClearCache(typeof(TForm).FullName);
        }

        public virtual async Task DeleteForm(TForm entity)
        {
            entity.Deleted = true;
            _formDbSet.Update(entity);
            await _erpContext.SaveChangesAsync();
            _cacheFormManager.ClearCache(typeof(TForm).FullName);
        }

        public virtual TForm CreateTempForm()
        {
            TForm form = new BaseForm() as TForm;

            form.Id = Guid.NewGuid();
            form.FormNbr = "<NEW>";
            form.CreatedOn = DateTime.Now;
            form.Status = FormStatus.Pending;
            // will add created by user here

            return form;
        }

        #endregion

        #region Form Item CRUD

        public virtual async Task<TItem> GetItemById(Guid id)
        {
            return await _formItemDbSet.FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<IEnumerable<TItem>> GetItemsByFormId(Guid formId)
        {
            return _cacheFormItemManager.EntityCacheNotExists(formId) ?
                _cacheFormItemManager.GenerateCache(_formItemDbSet.Where(c => c.FormId == formId).AsEnumerable(), formId)
                : _cacheFormItemManager.GetEntityCacheData(formId);
        }

        public virtual async Task<IEnumerable<TItem>> GetItemList()
        {
            return _cacheFormItemManager.EntityCacheNotExists(typeof(TItem).FullName) ?
                _cacheFormItemManager.GenerateCache(_formItemDbSet.AsEnumerable(), typeof(TItem).FullName)
                : _cacheFormItemManager.GetEntityCacheData(typeof(TItem).FullName);
        }

        public virtual async Task InsertItem(TItem formItem)
        {
            // will to add temporary insertion in temp table
        }

        public virtual async Task UpdateItem(TItem formItem)
        {

        }

        public virtual async Task DeleteItem(TItem formItem)
        {

        }

        #endregion
    }
}
