using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using RA.Core.Data;
using RA.Core.DataCaching.CacheManagement;
using RA.Core.PluginData.FormTypes;
using RA.Data.Domain.DataChanges;
using RA.FormTypes.Data;
using RA.FormTypes.Domain;
using RA.WebFramework.Extensions;
using RAerp.Services.DataChangeServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.FormTypes.Services
{
    /// <summary>
    /// Base Service of Forms
    /// this also include CRUD of Form Item
    /// </summary>
    /// <typeparam name="TForm">Base Form</typeparam>
    /// <typeparam name="TItem">Base Form Item</typeparam>
    /// <typeparam name="TSettings">Base Form Setting</typeparam>
    /// <typeparam name="TContext">Context data of Form</typeparam>
    public class FormItemService<TForm, TItem, TSettings, TContext> : IFormItemService<TForm, TItem, TSettings, TContext> 
        where TForm : BaseForm
        where TItem : BaseFormItem
        where TSettings : BaseFormSetting
        where TContext : DbContext
    {
        #region Constants
        private readonly TContext _erpContext;
        private readonly ICacheManager<TForm> _cacheFormManager;
        private readonly ICacheManager<TItem> _cacheFormItemManager;
        private readonly IFormTypeManager _formTypeManager;
        private readonly IDataChangeService _dataChangeService;
        #endregion

        #region Ctor
        public FormItemService(TContext erpContext,
            ICacheManager<TForm> cacheFormManager,
            ICacheManager<TItem> cacheFormItemManager,
            IFormTypeManager formTypeManager,
            IDataChangeService dataChangeService)
        {
            _erpContext = erpContext;
            _cacheFormManager = cacheFormManager;
            _cacheFormItemManager = cacheFormItemManager;
            _formTypeManager = formTypeManager;
            _dataChangeService = dataChangeService;
        }
        #endregion

        #region Form CRUD

        public virtual async Task<TForm> GetFormByIdAsync(Guid id)
        {
            return await _erpContext.Set<TForm>().FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<TForm> GetFormByFormNbrAsync(string formNbr)
        {
            return await _erpContext.Set<TForm>().FirstOrDefaultAsync(c => c.FormNbr == formNbr);
        }

        public virtual async Task<IEnumerable<TForm>> GetFormListAsync()
        {
            return _cacheFormManager.EntityCacheNotExists(typeof(TForm).FullName) ?
                await _cacheFormManager.GenerateCacheAsync(await _erpContext.Set<TForm>().ToListAsync(), typeof(TForm).FullName)
                : _cacheFormManager.GetEntityCacheData(typeof(TForm).FullName);
        }

        public virtual async Task InsertFormAsync(TForm form)
        {
            var tempFormId = form?.Id;
            // get settings
            var settings = await _formTypeManager.GetSettingDataOfFormAsync<TForm, TSettings>();
            if (settings.AutoGeneratedFormNbr)
            {
                form.FormNbr = await _formTypeManager.GetCurrentTemplateOfFormAsync<TForm, TSettings>();

                await _formTypeManager.IncreaseTemplateCountOfFormAsync<TForm, TSettings>();
            }
            else
            {
                if (string.IsNullOrEmpty(settings.FormNbrTemplate))
                {
                    // use TEMP for now
                    // will add database table for this
                    form.FormNbr = "<TEMP>";
                }
            }

            if (settings.OpenDocOnCreate)
            {
                form.Status = FormStatus.Open;
            }
            else
            {
                form.Status = FormStatus.Onhold;
            }

            form.Id = Guid.NewGuid();
            form.CreatedOn = DateTime.UtcNow;

            await using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                await _erpContext.Set<TForm>().AddAsync(form);
                // need to add insert form item here..
                if (tempFormId.IsNotNullOrEmpty() && settings.AllowAddItemEnabled)
                {
                    var dataChanges = await _dataChangeService.GetListByDataIdAsync(tempFormId.Value);
                    foreach (var item in dataChanges)
                    {
                        if (string.IsNullOrEmpty(item.Record) || item.Status != DataChangeStatus.Insert)
                            continue;

                        TItem formItem = JsonConvert.DeserializeObject<TItem>(item.Record);
                        formItem.FormId = form.Id;
                        await InsertItemAsync(formItem);
                        // delete data change
                        await _dataChangeService.DeleteAsync(item);
                    }
                }
                await _erpContext.SaveChangesAsync();
                _cacheFormManager.ClearCache(typeof(TForm).FullName);
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
            
        }

        public virtual async Task UpdateFormAsync(TForm form)
        {
            form.ModifiedOn = DateTime.UtcNow;
            await using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TForm>().Update(form);
                // get changed items
                var dataChanges = await _dataChangeService.GetListByDataIdAsync(form.Id);
                foreach (var item in dataChanges)
                {
                    if (string.IsNullOrEmpty(item.Record) || item.Status != DataChangeStatus.Update)
                        continue;

                    TItem formItem = JsonConvert.DeserializeObject<TItem>(item.Record);
                    await UpdateItemAsync(formItem);
                    // delete data change
                    await _dataChangeService.DeleteAsync(item);
                }
                await _erpContext.SaveChangesAsync();
                _cacheFormManager.ClearCache(typeof(TForm).FullName);
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
        }

        public virtual async Task DeleteFormAsync(TForm form)
        {
            form.Deleted = true;
            form.ModifiedOn = DateTime.UtcNow;
            await using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TForm>().Update(form);
                // get changed items
                var dataChanges = await _dataChangeService.GetListByDataIdAsync(form.Id);
                foreach (var item in dataChanges)
                {
                    if (string.IsNullOrEmpty(item.Record) || item.Status != DataChangeStatus.Delete)
                        continue;

                    TItem formItem = JsonConvert.DeserializeObject<TItem>(item.Record);
                    await DeleteItemAsync(formItem);
                    // delete data change
                    await _dataChangeService.DeleteAsync(item);
                }
                await _erpContext.SaveChangesAsync();
                _cacheFormManager.ClearCache(typeof(TForm).FullName);
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
            
        }

        public virtual TForm CreateTempForm()
        {
            TForm form = (TForm)Activator.CreateInstance(typeof(TForm));

            form.Id = Guid.NewGuid();
            form.FormNbr = "<NEW>";
            form.CreatedOn = DateTime.UtcNow;
            form.Status = FormStatus.Pending;

            return form;
        }

        #endregion

        #region Form Item CRUD

        public virtual async Task<TItem> GetItemByIdAsync(Guid id)
        {
            return await _erpContext.Set<TItem>().FirstOrDefaultAsync(c => c.Id == id);
        }

        public virtual async Task<IEnumerable<TItem>> GetItemsByFormIdAsync(Guid formId)
        {
            IEnumerable<TItem> formItems = _cacheFormItemManager.EntityCacheNotExists(formId) ?
                                            await _cacheFormItemManager.GenerateCacheAsync(await _erpContext.Set<TItem>().Where(c => c.FormId == formId).ToListAsync(), formId)
                                            : _cacheFormItemManager.GetEntityCacheData(formId);

            IEnumerable<DataChange> dataChangeList = await _dataChangeService.GetListByDataIdAsync(formId);
            if (dataChangeList.Any())
            {
                var formItemsList = formItems.Any() ? formItems.ToList() : new List<TItem>();
                foreach (var dataChange in dataChangeList.OrderBy(c => c.CreatedOn))
                {
                    if (dataChange.Record.IsNotNullOrEmptyJson())
                    {
                        TItem formItem = JsonConvert.DeserializeObject<TItem>(dataChange.Record);
                        if (formItemsList.Any(c => c.CatalogId == formItem.CatalogId) && dataChange.Status != DataChangeStatus.Delete)
                        {
                            formItemsList.Remove(formItem);
                            // re-add updated form item
                            formItemsList.Add(formItem);
                        }
                        else
                        {
                            if (!formItems.Any())
                                formItemsList.Add(formItem);
                        }
                    }
                }
                formItems = formItemsList.OrderBy(c => c.LineNbr);
            }

            return formItems.ToList();
        }

        public virtual async Task<IEnumerable<TItem>> GetItemListAsync()
        {
            return _cacheFormItemManager.EntityCacheNotExists(typeof(TItem).FullName) ?
                await _cacheFormItemManager.GenerateCacheAsync(await _erpContext.Set<TItem>().ToListAsync(), typeof(TItem).FullName)
                : _cacheFormItemManager.GetEntityCacheData(typeof(TItem).FullName);
        }

        public virtual async Task<TItem> GetItemByFormIdAndCatalogId(Guid formId, Guid catalogId)
        {
            return await _erpContext.Set<TItem>().FirstOrDefaultAsync(c => c.FormId == formId && c.CatalogId == catalogId);
        }

        public virtual async Task InsertItemAsync(TItem formItem, bool saveChangesToDb = false)
        {
            formItem.CreatedOn = DateTime.UtcNow;
            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                await _erpContext.Set<TItem>().AddAsync(formItem);
                if (saveChangesToDb)
                {
                    await _erpContext.SaveChangesAsync();
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                else
                {
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
            
        }

        public virtual async Task UpdateItemAsync(TItem formItem, bool saveChangesToDb = false)
        {
            formItem.ModifiedOn = DateTime.UtcNow;
            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TItem>().Update(formItem);
                if (saveChangesToDb)
                {
                    await _erpContext.SaveChangesAsync();
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                else
                {
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
        }

        public virtual async Task DeleteItemAsync(TItem formItem, bool saveChangesToDb = false)
        {
            formItem.DeletedOn = DateTime.UtcNow;
            formItem.Deleted = true;
            using var transaction = await _erpContext.Database.BeginTransactionAsync();
            try
            {
                _erpContext.Set<TItem>().Update(formItem);
                if (saveChangesToDb)
                {
                    await _erpContext.SaveChangesAsync();
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                else
                {
                    _cacheFormItemManager.ClearCache(formItem.FormId);
                }
                await transaction.CommitAsync();
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                throw new Exception(ex?.Message);
            }
        }

        public virtual async Task<TItem> GetTempItemAsync(Guid formId, Guid catalogId)
        {
            if (formId.IsNullOrEmpty() || catalogId.IsNullOrEmpty())
                throw new ArgumentNullException("Cannot retrieve temp item");

            var dataChangeItem = await _dataChangeService.GetByDataIdAndItemDataIdAsync(formId, catalogId);
            if (dataChangeItem == null)
                return null;

            if (dataChangeItem.Record.IsNullOrEmptyJson())
                return null;

            var orderItem = JsonConvert.DeserializeObject<TItem>(dataChangeItem.Record);

            return orderItem;
        }

        public virtual async Task InsertTempItemAsync(TItem formItem, DataChangeStatus dataChangeStatus)
        {
            if (formItem == null)
                throw new ArgumentNullException("Form Item is null cannot insert data change item");

            DataChange dataChange = null;

            dataChange = await _dataChangeService.GetByDataIdAndItemDataIdAsync(formItem.FormId, formItem.CatalogId);
            if (dataChange == null)
            {
                dataChange = new DataChange();
                dataChange.DataId = formItem.FormId;
                dataChange.ItemDataId = formItem.CatalogId;
                dataChange.SystemName = typeof(TItem).FullName;
                dataChange.Status = dataChangeStatus;
                dataChange.Record = JsonConvert.SerializeObject(formItem);
                await _dataChangeService.InsertAsync(dataChange);
            }
            else
            {
                dataChange.Record = JsonConvert.SerializeObject(formItem);
                await _dataChangeService.UpdateAsync(dataChange);
            }
        }

        #endregion

        #region Methods
        public virtual Task<List<TForm>> ToPagedListAsync(IEnumerable<TForm> query, int pageNumber, int pageSize)
        {
            // Default values
            if (pageNumber <= 0)
                pageNumber = 1;

            if (pageSize <= 0)
                pageSize = 10;

            // Skip rows
            var skip = (pageNumber - 1) * pageSize;

            // Fetch paged data (synchronous LINQ — works for both in-memory and EF queryables)
            var result = query.Skip(skip).Take(pageSize).ToList();

            return Task.FromResult(result);
        }
        #endregion
    }
}
