using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.FormTypes.Data
{
    /// <summary>
    /// Base Setting of Forms
    /// </summary>
    public class BaseFormSetting
    {
        public string SystemName { get; set; }
        public string FormNbrTemplate { get; set; }
        public int FormNbrIncrementCount { get; set; }
        public int FormNbrCount { get; set; }
        public bool AutoGeneratedFormNbr { get; set; }
        public bool CreateEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public bool DeleteEnabled { get; set; }
        public bool Installed { get; set; }
        public bool Enabled { get; set; }
        public bool AllowAddItemEnabled { get; set; }
        public bool AllowEditDateEnabled { get; set; }
        public bool InlineAddEnabled { get; set; }
        public bool ApprovalEnabled { get; set; }
        public bool OpenDocOnCreate { get; set; }
        public bool InventoryEnabled { get; set; }
        public bool RedirectUsingFormNbrEnabled { get; set; }
        public bool ShowItemCodeInGrid { get; set; }
        public bool FormApiEnabled { get; set; }
        public int ItemsPageSize { get; set; } // default 10
    }
}
