<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputPath>..\..\..\RAerp\Plugins\RA.WebServiceEndpoints</OutputPath>
		<OutDir>$(OutputPath)</OutDir>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Views\Create.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\Index.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\List.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\_WebServiceEndpointList.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\_CreateAndEdit.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\_CreateAndEdit.General.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\_CreateAndEdit.System.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Views\_ViewImports.cshtml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\CoreModules\RA.EntityTypes\RA.EntityTypes.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
		<ProjectReference Include="..\..\..\CoreModules\RA.FormTypes\RA.FormTypes.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
		<ProjectReference Include="..\..\..\RAerp\RAerp.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
		<ProjectReference Include="..\..\EntityTypes\RA.BusinessEntities\RA.BusinessEntities.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
		<ProjectReference Include="..\..\EntityTypes\RA.Categories\RA.Categories.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<CopyLocal>False</CopyLocal>
		</ProjectReference>
	</ItemGroup>

</Project>
