<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<OutputPath>..\..\RAerp\Plugins\RA.EntityTypes</OutputPath>
	<OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Views\ChildEntityTypeList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\CreateChildEntity.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ChildEntityTypeListSearch.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_EntityTypeList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\Libraries\RA.Core\RA.Core.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	  <ProjectReference Include="..\..\Libraries\RA.Data\RA.Data.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	<ProjectReference Include="..\..\RAerp\RAerp.csproj">
		<Private>False</Private>
		<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		<CopyLocal>False</CopyLocal>
	</ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
