<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<OutputPath>..\..\RAerp\Plugins\RA.EntityTypes</OutputPath>
	<OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Views\ChildEntityTypeList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\CreateChildEntity.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ChildEntityTypeListSearch.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_EntityTypeList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\Libraries\RA.Core\RA.Core.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	  <ProjectReference Include="..\..\Libraries\RA.Data\RA.Data.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
	<ProjectReference Include="..\..\RAerp\RAerp.csproj">
		<Private>False</Private>
		<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		<CopyLocal>False</CopyLocal>
	</ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentMigrator" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
  </ItemGroup>

</Project>
