<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentMigrator" Version="7.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\Inventory\" />
    <Folder Include="Domain\Sales\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RA.Core\RA.Core.csproj" />
  </ItemGroup>

</Project>
