<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domain\Inventory\**" />
    <EmbeddedResource Remove="Domain\Inventory\**" />
    <None Remove="Domain\Inventory\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\" />
    <Folder Include="Domain\Sales\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RA.WebFramework\RA.WebFramework.csproj" />
    <ProjectReference Include="..\RA.Core\RA.Core.csproj" />
  </ItemGroup>

</Project>
