<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\Inventory\" />
    <Folder Include="Domain\Sales\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RA.Core\RA.Core.csproj" />
  </ItemGroup>

</Project>
