using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.Core.Models.UserInfaceModels
{
    /// <summary>
    /// Serves as user interface accessibility
    /// for different controls in the UI
    /// </summary>
    public class UserInterfaceAccessModel
    {
        #region CRUD Controls
        public bool ViewEnabled { get; set; }
        public bool CreateEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public bool DeleteEnabled { get; set; }

        public bool AutoGeneratedTemplate { get; set; }
        public bool ModalCreationEnabled { get; set; }
        public bool RedirectUsingCodeEnabled { get; set; }
        public bool InlineEditEnabled { get; set; }
        #endregion
    }
}
