<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<OutputPath>..\..\..\RAerp\Plugins\RA.BusinessEntities</OutputPath>
	<OutDir>$(OutputPath)</OutDir>
	<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\Create.cshtml" />
    <None Remove="Views\Index.cshtml" />
    <None Remove="Views\List.cshtml" />
    <None Remove="Views\_CreateAndEdit.cshtml" />
    <None Remove="Views\_CreateAndEdit.General.cshtml" />
    <None Remove="Views\_CreateAndEdit.System.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\Configuration.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Components\_BusinessEntityTest.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Index.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Create.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\List.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.Address.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.General.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_Configuration.Main.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_Configuration.Mapping.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_BusinessEntityList.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_CreateAndEdit.System.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CoreModules\RA.EntityTypes\RA.EntityTypes.csproj">
		<Private>False</Private>
		<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		<CopyLocal>False</CopyLocal>
	</ProjectReference>
    <ProjectReference Include="..\..\..\RAerp\RAerp.csproj">
		<Private>False</Private>
	    <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
	    <CopyLocal>False</CopyLocal>
	</ProjectReference>
	  <ProjectReference Include="..\RA.Categories\RA.Categories.csproj">
		  <Private>False</Private>
		  <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		  <CopyLocal>False</CopyLocal>
	  </ProjectReference>
  </ItemGroup>

</Project>
