using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.Core.Models.PluginModels.FormTypes
{
    /// <summary>
    /// Base configure model of forms
    /// </summary>
    public class BaseFormConfigureModel
    {
        public string SystemName { get; set; }
        [DisplayName("Form No. Template")]
        public string FormNbrTemplate { get; set; }
        [DisplayName("Form No. Increment Count")]
        public int FormNbrIncrementCount { get; set; }
        [DisplayName("Form No. Count")]
        public int FormNbrCount { get; set; }
        [DisplayName("Auto Generate Form Nbr")]
        public bool AutoGeneratedFormNbr { get; set; }
        public bool CreateEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public bool DeleteEnabled { get; set; }
        public bool Installed { get; set; }
        public bool Enabled { get; set; }
        [DisplayName("Allow Add Item")]
        public bool AllowAddItemEnabled { get; set; }
        [DisplayName("Allow Edit Date")]
        public bool AllowEditDateEnabled { get; set; }
        [DisplayName("Inline Add Enabled")]
        public bool InlineAddEnabled { get; set; }
        [DisplayName("Approval Enabled")]
        public bool ApprovalEnabled { get; set; }
        [DisplayName("Open Doc on Create")]
        public bool OpenDocOnCreate { get; set; }
        [DisplayName("Inventory Enabled")]
        public bool InventoryEnabled { get; set; }
        [DisplayName("Redirect by Form No. Enabled")]
        public bool RedirectUsingFormNbrEnabled { get; set; }
        [DisplayName("Show Item Code in grid")]
        public bool ShowItemCodeInGrid { get; set; }
        [DisplayName("Form API Enabled")]
        public bool FormApiEnabled { get; set; }
        [DisplayName("Items Tab Page Size")]
        public int ItemsPageSize { get; set; }
    }
}
