using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RA.Core.Models.PluginModels.FormTypes
{
    public class FormSettingsModel
    {
        public string SystemName { get; set; }
        public string FormNbrTemplate { get; set; }
        public int FormNbrIncrementCount { get; set; }
        public int FormNbrCount { get; set; }
        public bool AutoGeneratedFormNbr { get; set; }
        public bool CreateEnabled { get; set; }
        public bool UpdateEnabled { get; set; }
        public bool DeleteEnabled { get; set; }
        public bool Installed { get; set; }
        public bool Enabled { get; set; }
        public bool AllowAddItemEnabled { get; set; }
        public bool AllowEditDateEnabled { get; set; }
        public bool InlineAddEnabled { get; set; }
        public bool ApprovalEnabled { get; set; }
        public bool OpenDocOnCreate { get; set; }
        public bool InventoryEnabled { get; set; }
        public bool RedirectUsingFormNbrEnabled { get; set; }
        public bool ShowItemCodeInGrid { get; set; }
        public int ItemsPageSize { get; set; }
        public List<Guid> MappedCatalogTypeIds { get; set; }
        public List<Guid> MappedServiceTypeIds { get; set; }
        public List<Guid> MappedCategoryTypeIds { get; set; }
    }
}
